title: Keynote
modelClass: Dt\Notes\Models\Keynote
list: $/dt/notes/models/keynote/columns.yaml
recordUrl: 'dt/notes/keynote/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
