title: Section
modelClass: Dt\Notes\Models\Section
list: $/dt/notes/models/section/columns.yaml
recordUrl: 'dt/notes/section/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
